name: Generate Snake

on:
  schedule: # ejecuta todos los días a la medianoche
    - cron: "0 0 * * *"
  workflow_dispatch: # permite ejecutarlo manualmente desde Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: luciaduque248
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated Snake"
          add: "dist/snake.svg"
